INSERT INTO categories (category_name) VALUES
                                           ('Fiction'),
                                           ('Non-fiction'),
                                           ('Science Fiction'),
                                           ('Fantasy'),
                                           ('Biography'),
                                           ('Historical Fiction'),
                                           ('Mystery'),
                                           ('Thriller'),
                                           ('Children\'s Books'),
                                           ('Young Adult'),
                                           ('Romance'),
                                           ('Self-Help'),
                                           ('Cookbooks'),
                                           ('Art & Photography'),
                                           ('Travel'),
                                           ('Health & Wellness'),
                                           ('Politics'),
                                           ('Business & Economics'),
                                           ('Science'),
                                           ('Technology'),
                                           ('Sports & Recreation'),
                                           ('Psychology'),
                                           ('Education'),
                                           ('Poetry'),
                                           ('True Crime'),
                                           ('Horror'),
                                           ('Literary Fiction'),
                                           ('Comic Books'),
                                           ('Graphic Novels'),
                                           ('Religion & Spirituality');
